// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDySR0VXlXqsUaQLTgAm6zO5t2CIO3PrLk',
    appId: '1:901924478892:web:675f4e17703ef2e757a409',
    messagingSenderId: '901924478892',
    projectId: 'shop-app-a8b3b',
    authDomain: 'shop-app-a8b3b.firebaseapp.com',
    databaseURL: 'https://shop-app-a8b3b-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-a8b3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDzSlT7AvgV5_X9jNz_1cNB-5K3_NRkMs',
    appId: '1:901924478892:android:c090183e66f7508e57a409',
    messagingSenderId: '901924478892',
    projectId: 'shop-app-a8b3b',
    databaseURL: 'https://shop-app-a8b3b-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-a8b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSFUgIF4fyBhxWWtmS1ta7DLzlDTh5-AQ',
    appId: '1:901924478892:ios:66c7eeeea550215b57a409',
    messagingSenderId: '901924478892',
    projectId: 'shop-app-a8b3b',
    databaseURL: 'https://shop-app-a8b3b-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-a8b3b.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSFUgIF4fyBhxWWtmS1ta7DLzlDTh5-AQ',
    appId: '1:901924478892:ios:66c7eeeea550215b57a409',
    messagingSenderId: '901924478892',
    projectId: 'shop-app-a8b3b',
    databaseURL: 'https://shop-app-a8b3b-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-a8b3b.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDySR0VXlXqsUaQLTgAm6zO5t2CIO3PrLk',
    appId: '1:901924478892:web:5a37be2c82b3bc9f57a409',
    messagingSenderId: '901924478892',
    projectId: 'shop-app-a8b3b',
    authDomain: 'shop-app-a8b3b.firebaseapp.com',
    databaseURL: 'https://shop-app-a8b3b-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-a8b3b.firebasestorage.app',
  );
}
